### PR TITLE
Move prompt logic from webworks-cli to cordova-cli

### PR DESCRIPTION
**Pull request by jsoref**
Follow up to https://issues.apache.org/jira/browse/CB-6241

### CODE REVIEW

**Comment by bryanhiggins** [comment]
There should be no need for the special handling at all now.

**Comment by jsoref** [comment]
Isn't that what I've done? 

Remember that commander will abort if you pass it unexpected arguments including --query

**Comment by bryanhiggins** [comment]
We put this special handling in for two reasons:
1) Real time console logging
2) Pass in query param

Neither of these are needed now, so we can drop this entirely and rely on cordova-cli

**Comment by bryanhiggins** [comment]
Merged

**Pull request closed without merging**
